import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

const url = (p: string) => new URL(p, import.meta.url);
const read = (p: string) => readFileSync(url(p), "utf8");

describe("client UI source (shipped public assets)", () => {
  it("has desktop landscape and mobile portrait layouts", () => {
    const css = read("../public/css/app.css");
    assert.match(css, /orientation:\s*portrait/);
    assert.match(css, /orientation:\s*landscape/);
    assert.match(css, /max-width:\s*820px/);
    assert.match(css, /\.felt/);
    assert.match(css, /aspect-ratio:\s*2\.2\s*\/\s*1/);
    assert.match(css, /aspect-ratio:\s*1\s*\/\s*1\.65/);
    assert.match(css, /border-radius:\s*999px/);
    assert.match(css, /\.seat/);
    assert.match(css, /\.pchip/);
    assert.match(css, /@keyframes dealIn/);
    assert.match(css, /@keyframes pulse/);
    assert.match(css, /@keyframes sdIn/);
    assert.match(css, /\.deal-anim/);
    assert.match(css, /is-showdown \.center-stack/);
    assert.match(css, /\.sd-holes/);
    assert.match(css, /\.showdown\s*\{[^}]*position:\s*fixed/s);
    assert.match(css, /\.showdown\s*\{[^}]*place-items:\s*center/s);
    assert.match(css, /\.seat-cd/);
    const js = read("../public/js/app.js");
    assert.match(js, /seat-cd/);
    assert.doesNotMatch(js, /行动倒计时/);
    assert.match(js, /PORTRAIT_SEATS/);
    assert.match(js, /LANDSCAPE_SEATS/);
    assert.match(css, /\.table-rules/);
    assert.match(css, /--rail-w/);
    assert.match(css, /\.hole\s*\{[^}]*grid-column:\s*2/s);
    assert.match(css, /\.seat\.vis-0 \.bet/);
    assert.match(css, /\.dock\s*\{[^}]*min-height/s);
    assert.match(css, /\.actions\s*\{[^}]*flex-direction:\s*column/s);
    assert.match(css, /\.amount-controls/);
    assert.match(css, /\.amount-panel\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*102px/s);
    assert.match(css, /\.amount-submit\s*\{[^}]*height:\s*69px/s);
    assert.match(css, /\.action-row/);
    assert.match(css, /\.action-row button\s*\{[^}]*height:\s*48px/s);
    assert.match(css, /\.raise-presets button\s*\{[^}]*height:\s*32px/s);
    assert.match(css, /\.modal-actions\s*\{[^}]*grid-template-columns/s);
    assert.match(js, /raiseOpen/);
    assert.match(js, /data-close-amount/);
    assert.match(js, /vis-\$\{vis\}/);
    assert.doesNotMatch(js, /STREET/);
    assert.doesNotMatch(js, /id="btn-rebuy"/);
    assert.match(css, /orientation:\s*portrait[\s\S]*\.showdown\s*\{[\s\S]*position:\s*fixed/);
    assert.match(css, /#table-screen\.screen\s*\{[^}]*height:\s*100dvh[^}]*overflow:\s*hidden/s);
    assert.match(css, /height:\s*min\(100%,\s*calc\(96vw \* 1\.65\)\)/);
    assert.match(css, /@media \(min-width:\s*821px\)[\s\S]*\.hole\s*\{[^}]*left:\s*50%[^}]*transform:\s*translate\(-50%,\s*-20px\)[^}]*\}[\s\S]*\.actions\s*\{[^}]*left:\s*calc\(50% \+ 82px\)/);
    assert.match(css, /@media \(min-width:\s*821px\)[\s\S]*\.amount-submit\s*\{[^}]*height:\s*52px[^}]*\}[\s\S]*\.action-row button\s*\{[^}]*height:\s*38px[^}]*\}[\s\S]*\.raise-presets button\s*\{[^}]*height:\s*26px[^}]*\}[\s\S]*\.raise-ctl\s*\{[^}]*height:\s*24px[^}]*\}/);
    const html = read("../public/index.html");
    assert.match(html, /id="table-rules"/);
    assert.match(html, /<footer class="dock">[\s\S]*id="showdown"/);
    assert.doesNotMatch(html, /id="felt"[\s\S]*id="showdown"[\s\S]*class="dock"/);
  });

  it("has invite copy, action controls, and is not Node-only", () => {
    const js = read("../public/js/app.js");
    const html = read("../public/index.html");
    assert.match(html, /复制邀请链接/);
    assert.doesNotMatch(html, /复制号码\+密码/);
    assert.doesNotMatch(html, /id="table-clock"/);
    assert.match(html, /id="btn-leave"/);
    assert.match(html, /id="btn-ai"[^>]*desktop-only[\s\S]*id="btn-ai-label">AI玩家/);
    assert.match(html, /id="ai-modal"/);
    assert.match(html, /id="ai-use-proxy"/);
    assert.match(html, /id="confirm-modal"/);
    assert.match(html, /icon-btn/);
    assert.match(js, /clipboard\.writeText/);
    assert.match(js, /inviteUrl/);
    assert.match(js, /data-act="fold"/);
    assert.match(js, /data-act="raise"/);
    assert.doesNotMatch(js, /\brequire\s*\(/);
    assert.doesNotMatch(js, /\bmodule\.exports\b/);
    assert.match(js, /new WebSocket/);
    assert.match(js, /new BrowserAiAgents\(getApiOrigin, renderAiPanel\)/);
    assert.match(js, /gameConfirm/);
    assert.doesNotMatch(js, /\bconfirm\s*\(/);
    assert.match(js, /markAiHost\(data\.snapshot\.tableNumber\)/);
    assert.match(js, /getApiOrigin/);
    assert.match(js, /config\.json/);
    assert.match(js, /document\.getElementById/);
    assert.match(js, /chipStackHTML/);
    assert.match(html, /Easy Poker/);
    assert.match(html, /退出游戏桌/);
    assert.match(js, /leaveTable/);
    assert.match(js, /ep\.table/);
    assert.match(js, /ep\.nick/);
    assert.match(js, /isPortraitTable/);
    assert.match(js, /queueDeals/);
    assert.match(js, /const handEnded = Boolean\(snap\.lastResult && !snap\.street\)/);
    assert.match(js, /state\.dealQueue = state\.dealQueue\.filter\(\(item\) => item\.where !== "hole"\)/);
    assert.match(js, /renderShowdown/);
    assert.match(js, /renderActions\(snap\);[\s\S]*queueDeals\(snap\);[\s\S]*}\s*renderShowdown\(snap\);\s*updateCountdown\(snap\);/);
    assert.match(js, /visualKey/);
    assert.match(html, /本手结算/);
    assert.match(js, /SEATS = 8/);
    assert.match(js, /actionMsLeft/);
    assert.match(js, /left === 0/);
    assert.match(html, /id="short-deck"/);
    assert.match(html, /翻牌后逼退对手将自动亮牌，每人支付 5BB/);
    assert.match(html, /id="emote-picker"/);
    assert.match(js, /data-preset="0\.333333"/);
    assert.match(js, /data-preset="0\.5"/);
    assert.match(js, /data-preset="1"/);
    assert.match(js, /data-preset="allin"/);
    assert.match(js, /preset\.dataset\.preset === "allin"\) slider\.value = slider\.max/);
    assert.match(js, /class="amount-controls"[\s\S]*class="raise-presets"[\s\S]*class="raise-ctl"/);
    assert.match(js, /data-submit-amount/);
    assert.match(js, /data-submit-label/);
    assert.match(js, /data-emoji/);
    assert.doesNotMatch(js, /亮出 27 杂色，领取奖励/);
    assert.match(js, /获得 27 杂色奖励/);
    assert.doesNotMatch(js, /if \(state\.showdownHand === hn\) return/);
  });

  it("ships persistent browser AI management without changing the CLI agent", () => {
    const manager = read("../public/js/ai-agents.js");
    const core = read("../public/js/agent-core.js");
    const cli = read("../scripts/agent.mjs");
    assert.match(manager, /easy-poker\.ai\.profiles\.v1/);
    assert.match(manager, /easy-poker\.ai\.tables\.v1/);
    assert.match(manager, /AES-GCM/);
    assert.match(manager, /navigator\.locks/);
    assert.match(manager, /type:\s*"join"/);
    assert.match(manager, /type:\s*"sit"/);
    assert.match(manager, /type:\s*"stand"/);
    assert.match(manager, /type:\s*"action"/);
    assert.match(manager, /proxyOrigin:\s*await this\.getApiOrigin\(\)/);
    assert.match(core, /export async function decide/);
    assert.doesNotMatch(cli, /agent-core|ai-agents/);
  });

  it("splits UI and API across two Workers", () => {
    const apiToml = read("../wrangler.toml");
    const webToml = read("../wrangler.web.toml");
    assert.match(apiToml, /name = "easy-poker-api"/);
    assert.match(apiToml, /class_name = "TableDO"/);
    assert.doesNotMatch(apiToml, /\[assets\]/);
    assert.match(webToml, /name = "easy-poker"/);
    assert.match(webToml, /\[assets\]/);
    assert.match(webToml, /directory = "\.\/public"/);
    const index = read("../src/index.ts");
    assert.doesNotMatch(index, /env\.ASSETS/);
    assert.match(index, /Access-Control-Allow-Origin/);
    assert.match(index, /\/ws/);
    const tableDo = read("../src/table-do.ts");
    assert.match(tableDo, /ws\.send\(JSON\.stringify\(\{ type: "state", snapshot \}\)\)/);
    assert.match(index, /\/api\/tables/);
    assert.match(index, /\/api\/model-proxy/);
    const web = read("../src/web.ts");
    assert.match(web, /ASSETS\.fetch/);
    assert.match(web, /config\.json/);
    assert.match(web, /wrong_worker/);
    const docs = [read("../README.md"), read("../docs/architecture.md"), read("../docs/deploy.md")].join("\n");
    assert.match(docs, /wrangler/i);
    assert.match(docs, /Durable Object/);
    assert.match(docs, /easy-poker-api/);
    assert.match(docs, /两个 Worker/);
  });

  it("ships distinct 音效 for check / raise / fold / 发牌 / 结算", () => {
    const html = read("../public/index.html");
    for (const name of ["fold", "check", "bet-1", "bet-2", "bet-3", "allin", "deal", "shuffle-1", "tick", "win", "lose"]) {
      assert.match(html, new RegExp(`/sounds/${name}\\.m4a`));
      assert.equal(existsSync(fileURLToPath(url(`../public/sounds/${name}.m4a`))), true);
    }
    const js = read("../public/js/app.js");
    assert.match(js, /e\.type === "fold"/);
    assert.match(js, /once\("fold"\)/);
    assert.match(js, /once\("check"\)/);
    assert.match(js, /e\.type === "call"/);
    assert.match(js, /bet-1/);
    assert.match(js, /once\("allin"\)/);
    assert.match(js, /play\("deal"\)/);
    assert.match(js, /play\("shuffle"\)/);
    assert.match(js, /play\("tick"\)/);
    assert.match(js, /actingPlayerId === snap\.me\?\.id/);
    assert.match(js, /play\("win"\)/);
    assert.match(js, /play\("lose"\)/);
    assert.match(js, /SFX_POOL/);
    assert.match(js, /raise-val/);
    assert.match(js, /data-runout/);
    assert.match(js, /actionLock/);
  });
});
